-- ============================================================
-- Purpose of the Script:
-- This SQL script performs exploratory and analytical queries
-- on customer, product, and sales data from the data warehouse.
-- It analyzes distributions and performance metrics such as
-- customer counts by country and gender, product distribution
-- by category, average product cost, revenue contribution by
-- product categories and customers, and total items sold by
-- country. These insights help understand customer demographics,
-- product performance, and sales distribution.
-- ============================================================


-- Retrieve the number of customers grouped by country to analyze
-- the geographic distribution of customers.
SELECT
	country,
	COUNT(customer_key) AS Total_Customers
FROM gold.dim_customers
GROUP BY country
ORDER BY Total_Customers DESC;


-- Retrieve the number of customers grouped by gender to understand
-- the gender distribution within the customer base.
SELECT
	DISTINCT gender,
	COUNT(customer_key) AS Total_Customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY Total_Customers DESC;


-- Retrieve the number of products available in each category
-- to understand the distribution of products across categories.
SELECT
	category,
	COUNT(product_id) AS Total_Products
FROM gold.dim_products
GROUP BY category
ORDER BY Total_Products DESC;


-- Calculate the average product cost for each category to analyze
-- pricing differences across product categories.
SELECT
	category,
	AVG(cost) AS Average_Cost
FROM gold.dim_products
GROUP BY category
ORDER BY Average_Cost DESC;


-- Calculate the total revenue generated by each product category
-- by joining the sales fact table with the product dimension table.
SELECT
	p.category,
	SUM(f.sales_amount) AS Total_Revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY Total_Revenue DESC;


-- Calculate the total revenue generated by each customer
-- by joining sales data with customer information.
SELECT
	CONCAT(dc.first_name,' ',dc.last_name) AS Name,
	SUM(fs.sales_amount) AS Total_Revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON dc.customer_key = fs.customer_key
GROUP BY CONCAT(dc.first_name,' ',dc.last_name)
ORDER BY Total_Revenue DESC;


-- Calculate the total quantity of items sold in each country
-- by joining sales data with customer location information.
SELECT
	c.country,
	SUM(f.quantity) AS Total_Sold_Items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY Total_Sold_Items DESC;